- hosts: mining_rigs
  become: true
  become_method: sudo
  tasks:
  - name: system update
    apt: # this syntax is equivalent to apt-get update
      update_cache: yes
  - name: install git
    apt:
      name: git
      state: latest
  - name: upgrade packages to latest version
    apt:
      name: "*" # all packages
      state: latest
  - name: run dist upgrade
    apt:
      upgrade: dist
  - name: copy nvidia install
    copy:
      src: scripts/install.sh
      dest: /home/rtrade/install.sh
  - name: copy zabbix install
      src: scripts/zabbix_install.sh
      dest: /home/rtrade/zabbix_install.sh
  - name: run nvidia install
    command: /bin/bash /home/rtrade/install.sh 
  - name: run zabbix install
    command: /bin/bash /home/rtrade/zabbix_install.sh